version: "3.9"
services:
  bank_collection_app_backend:
    build: .
    ports:
      - "3001:3001"
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: bank_collection_db
